### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by jojal5** [jojal5/Extremes.jl#20]
- [x] Build documentation for tagged and latest versions (master branch) ~~all branches~~ with Documenter.jl
- [x] Complete _Getting Started_ for the basic usage of Extremes.jl
- [x] Complete _index.md_ of Extremes.jl (this is the landing page of the documentation)
- [x] Incorporate custom initial values for model fitting
- [x] Add the standardization of covariates
- [x] Add plot functions
- [ ] Perhaps better to hardcode a citation.bib file. ~~Add [Zenodo](https://zenodo.org/) integration. (needs admin rights -> @jojal5). See how to here: https://zenodo.org/account/settings/github/~~
- [x] ~~Add examples in the docstrings for type constructor, at least the ones that are exported~~
- [x] ~~**Add a `describe` function? (returns statistics and other useful bits of information)**~~
- [x] POT struct for calculation of return level
- [x] ~~BIC function for each models~~
- [x] ~~Change parameters names of Mamba's Chains struct~~
- [x] ~~plot function for MCMC chains~~
- [ ]  Correct the equation displays in the tutorial (e.g. in stationary Block Maxima)
- [ ] Refactor tests of MaximumLikelihoodFittedExtremeValueModel
- [ ] Make a clearer distinction between \phi and \sigma

**Comment by Balinus** [comment]
First post updated.
